#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jan  9 21:21:20 2021

@author: jamaj
"""

import Scheduler

def main():
    
    feedurls = ['http://feeds.bbci.co.uk/news/world/latin_america/rss.xml',
             "http://feeds.bbci.co.uk/news/rss.xml",
             'https://www.nytimes.com/svc/collections/v1/publish/https://www.nytimes.com/section/world/rss.xml',
             "https://www.yahoo.com/news/rss/world",
             'https://br.noticias.yahoo.com/rss',
             'https://au.news.yahoo.com/rss',
             'https://uk.news.yahoo.com/rss',
             'https://it.notizie.yahoo.com/rss',
             "https://www.yahoo.com/news/rss/" ,
             'https://www.buzzfeed.com/world.xml',
             'http://www.aljazeera.com/xml/rss/all.xml',
             'http://defence-blog.com/feed',
             'https://www.e-ir.info/category/blogs/feed/',
             'https://www.globalissues.org/news/feed',
             'https://www.thecipherbrief.com/feed',
             'https://worldnewssuperfast.blogspot.com/feeds/posts/default?alt=rss',
             'http://rss.cnn.com/rss/edition_world.rss',
             'https://www.theguardian.com/world/rss',
             'http://feeds.washingtonpost.com/rss/world',
             'https://www.cnbc.com/id/100727362/device/rss/rss.html',
             'https://timesofindia.indiatimes.com/rssfeeds/296589292.cms',
             'https://www.cnbc.com/id/19746125/device/rss/rss.xml',
             'https://fortune.com/feed',
             'https://www.ft.com/?format=rss',
             'https://www.rfi.fr/fr/contenu/general/rss',
             'https://www.rfi.fr/afrique/rss',
             'https://www.rfi.fr/ameriques/rss',
             'https://www.rfi.fr/asie-pacifique/rss',
             'https://www.rfi.fr/europe/rss',
             'https://www.rfi.fr/france/rss',
             'https://www.rfi.fr/moyen-orient/rss',
             'https://www.rfi.fr/economie/rss',
             'https://www.rfi.fr/science/rss',
             'https://www.investing.com/rss/news.rss',
             'https://seekingalpha.com/market_currents.xml',
             'https://economictimes.indiatimes.com/rssfeedsdefault.cms',
             'https://finance.yahoo.com/news/rssindex',
             'https://www.financialexpress.com/feed/',
             'https://www.business-standard.com/rss/home_page_top_stories.rss',
             'https://www.thehindubusinessline.com/?service=rss',
             'https://prod-qt-images.s3.amazonaws.com/production/bloombergquint/feed.xml',
             # 'https://www.globes.co.il/webservice/rss/rssfeeder.asmx/FeederNode?iID=1725',
             'https://www.moneyweb.co.za/feed/',
             'https://business.financialpost.com/feed/',
             'https://mjbizdaily.com/feed/',
             'https://www.bmmagazine.co.uk/feed/',
             'https://www.businessdailyafrica.com/latestrss.rss',
             'https://www.canadianbusiness.com/business-news/feed/',
             'https://www.yahoo.com/news/rss',
             # 'https://www.businesstravelnews.com/rss/business-travel-news',
             'http://rss.cnn.com/rss/money_topstories.rss',
             'https://businessday.ng/feed/',
             'https://www.biztrailblazer.com/feed',
             'https://www.revyuh.com/feed/',
             'http://businessnews.com.ng/feed/',
             'https://bbj.hu/site/assets/rss/rss.php',
             'http://www.birminghampost.co.uk/business/rss.xml',
             'https://www.businessnews.com.ph/feed/',
             'https://www.thailand-business-news.com/feed',
             'https://www.ibtimes.com.au/rss',
             'http://feeds.feedburner.com/JewishBusinessNews',
             'https://iotbusinessnews.com/feed/',
             'https://www.businessnews.com.au/rssfeed/latest.rss',
             'https://libn.com/feed/',
             'https://www.rt.com/rss/news/',
             'http://feeds.feedburner.com/ndtvnews-world-news',
             'http://www.npr.org/rss/rss.php?id=1004',
             'http://abcnews.go.com/abcnews/internationalheadlines',
             'https://www.spiegel.de/international/index.rss',
             'https://www.cbsnews.com/latest/rss/world',
             'https://sputniknews.com/export/rss2/world/index.xml',
             'http://www.independent.co.uk/news/world/rss',
             'http://www.cbc.ca/cmlink/rss-world',
             'https://www.abc.net.au/news/feed/52278/rss.xml',
             'http://feeds.feedburner.com/time/world',
             'https://time.com/feed',
             'https://www.thesun.co.uk/news/worldnews/feed/',
             'https://www.latimes.com/world/rss2.0.xml',
             'http://www.mirror.co.uk/news/world-news/rss.xml',
             'https://www.euronews.com/rss?level=theme&name=news',
             'https://www.vox.com/rss/world/index.xml',
             'http://feeds.skynews.com/feeds/rss/world.xml',
             'http://feeds.feedburner.com/daily-express-world-news',
             'http://www.smh.com.au/rssheadlines/world/article/rss.xml',
             'https://www.ctvnews.ca/rss/world/ctvnews-ca-world-public-rss-1.822289',
             # 'https://www.france24.com/en/rss',
             'https://www.scmp.com/rss/91/feed',
              'http://feeds.news24.com/articles/news24/World/rss',
             'https://globalnews.ca/world/feed/',
             'http://www.channelnewsasia.com/rssfeeds/8395884',
             'https://www.rawstory.com/category/world/feed/',
             'https://www.seattletimes.com/nation-world/world/feed/',
             'http://www.thestar.com/content/thestar/feed.RSSManagerServlet.articles.news.world.rss',
             # 'https://www.brookings.edu/topic/international-affairs/feed/',
             # 'http://www.washingtontimes.com/rss/headlines/news/world',
             # 'https://www.todayonline.com/feed/world',
             'https://www.dailytelegraph.com.au/news/world/rss',
             'https://feeds.breakingnews.ie/bnworld',
             # 'http://www1.cbn.com/cbnnews/world/feed'
             ]

   
    feeds = []
    for url in feedurls:
        feeds.append({'url':url, 'last':"", 'rss':{}, 'label':"", 'log':{ 'success': 0,'fail':0,'last_execution': {}   }  })

    Scheduler.json_write('rssfeeds.conf',feeds)
    
main()
